#! Make sure to add your token into .env

# The colors used for the bot (eg embed color)
colors: 
    ok: "#5865F2"
    error: "#ED4245"
    good: "#57F287"
    warning: "#FEE75C"

# The api's enabled for the bot
apiEnabled:
  reddit: true
  urbandictionary: true
  # (below) requires it in .env 
  topgg: true
  # (below) requires it in .env  
  deepai: true
  nekobot: true
  someRandomApi: true
  googletranslate: true
  randomSmallOnes: 
    pastegg: true
    rhymebrain: true
    awsrandomcat: true
    dogceo: true
    icanhazdadjoke: true
    forismatic: true
    affirmationsdev: true
    evilinsultcom: true
    excuserheroku: true
    uselessfactspl: true
    shibeonline: true
    randomduk: true
    zooanimalapiheroku: true
    emojihubheroku: true