# yaml-language-server: $schema=./config.schema.json
#? Make sure to add your token into .env

# The colors used for the bot (eg embed color)
colors: 
    ok: "#5865F2"
    error: "#ED4245"
    good: "#57F287"
    warning: "#FEE75C"
    washedOut:
      ok: "#586599"
      

# The api's enabled for the bot
apiEnabled:
  reddit: true
  urbanDictionary: true
  # (below) requires key in .env 
  topgg: true
  nekobot: true
  someRandomApi: true
  googleTranslate: true
  randomSmallOnes:
    randomImage: true
    randomText: true
