name: "Continuous Integration"

on:
  push:
    branches: 
      - main

  pull_request:
    branches:
      - '!gh-actions'
      - 'main'
      - '**'

jobs:
  typescript-build:
    runs-on: ubuntu-latest
    name: "TypeScript build"
    steps:
      - uses: actions/checkout@v3

      - name: Setup node.js v18
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: 'yarn'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Turbo cache
        id: turbo-cache
        uses: actions/cache@v2
        with:
          path: .turbo
          key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ github.job }}-${{ github.ref_name }}-
      
      - name: Add custom Problem Matchers
        run: |
          echo ::add-matcher::.github/problem-matchers/eslint-compact.json   
          echo ::add-matcher::.github/problem-matchers/eslint-stylish.json   
          echo ::add-matcher::.github/problem-matchers/tsc.json   

      - name: Install dependencies 
        # if: ${{ steps.yarn-cache.outputs.cache-hit != 'true' }}
        run: yarn install --immutable

      - name: Run Build
        # run: yarn build
        run: yarn turbo run build:ci --cache-dir=".turbo" && yarn tsc
      

  eslint:
    runs-on: ubuntu-latest
    name: "ESLint"
    steps:
      - uses: actions/checkout@v3

      - name: Setup node.js v18
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: 'yarn'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Turbo cache
        id: turbo-cache
        uses: actions/cache@v2
        with:
          path: .turbo
          key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ github.job }}-${{ github.ref_name }}-
            
      - name: Add custom Problem Matchers
        run: |
          echo ::add-matcher::.github/problem-matchers/eslint-compact.json   
          echo ::add-matcher::.github/problem-matchers/eslint-stylish.json   
          echo ::add-matcher::.github/problem-matchers/tsc.json   

      - name: Install dependencies 
        # if: ${{ steps.yarn-cache.outputs.cache-hit != 'true' }}
        run: yarn install --immutable

      - name: Run ESLint
        run: yarn turbo run lint --cache-dir=".turbo" && yarn eslint src/*.mts 
