# dependabout updates all, but i want to recursively update yarn.lock
name: More Dependabot

# run when dependabot updates package and opens a PR
on:
  pull_request:
    types: [opened, synchronize]

# Set the access for individual scopes, or use permissions: write-all
permissions:
  contents: write

jobs:
    recursive-update:
        runs-on: ubuntu-latest
        # if: github.actor == 'dependabot[bot]'
        name: Recursively update all dependencies
        steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        # - name: Install node.js
        #   uses: actions/setup-node@v3
        #   with:
        #     node-version: 'current'
        #     registry-url: https://registry.npmjs.org/
        #     cache: 'yarn'
        #     cache-dependency-path: yarn.lock

        # - name: Install dependencies
        #   run: yarn --immutable

        - run: |
            yarn up ** -R
          name: Recursively update all dependencies
        
        - run: git config --global user.name "dependabot[bot]"
        - run: git config --global user.email "dependabot[bot]@users.noreply.github.com"

        - name: Check for Changes and Commit
          run: |
            if git diff --quiet yarn.lock; then
                echo "No changes to file."
            else
                git add yarn.lock
                git commit -m "Recursively update all dependencies"
            fi
