# dependabout updates all, but i want to recursively update yarn.lock
name: More Dependabot

# run when dependabot updates package and opens a PR
on:
  push: 
    # branches:
    #   - dependabot/npm_and_yarn/**
  

# Set the access for individual scopes, or use permissions: write-all
permissions:
  contents: write

jobs:
    recursive-update:
        runs-on: ubuntu-latest
        # if: github.actor == 'dependabot[bot]'
        name: Recursively update dependencies
        steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Install node.js
          uses: actions/setup-node@v3
          with:
            node-version: 'current'
            registry-url: https://registry.npmjs.org/
            cache: 'yarn'
            cache-dependency-path: yarn.lock

        # - name: Install dependencies
        #   run: yarn --immutable

        - run: ./.github/scripts/recursive-update.sh
          shell: bash
          name: Recursively update
        
        - name: Configure git
          run: |
                git config --global user.name "dependabot[bot]"
                git config --global user.email "dependabot[bot]@users.noreply.github.com"

        - name: Commit
          run: |
                git add .
                git commit -m "Recursively update dependencies" || true
                git push
            
