name: Github Pages

on:
  push:
    branches:
      - main  # Set a branch to deploy
    paths:
      - "website/**"
  pull_request:
    branches:
      - main  # Set a branch to deploy
    paths:
      - "website/**"


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build
        run: ( cd website && hugo --minify )
        
      - name: Build artifact page
        run: ( cd website && hugo -b http://localhost -d publicLocalhost ) 

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Website
          path: ./website/publicLocalhost 

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/public
