name: Publish packages to NPM
on:
  workflow_run:
    workflows: ["Run Tests"]
    types: 
      - completed
    branches:
        - main

jobs:
  npm-publish:
    if: ${{ github.repository_owner == 'RiskyMH' }} && ${{ github.event.workflow_run.conclusion == 'success' }}
    name: npm publish
    strategy:
      fail-fast: false
      matrix:
        include:
          - package: '@riskybot/tools'
            folder: 'builders'
          - package: '@riskybot/commands'
            folder: 'commands'
          - package: '@riskybot/apis'
            folder: 'apis'
          - package: '@riskybot/image-generate'
            folder: 'image-generation'
          - package: 'discord-api-parser'
            folder: 'discord-api-parser'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
          cache: 'yarn'
          cache-dependency-path: yarn.lock

      - name: Install dependencies
        run: yarn --immutable

      - name: Turbo cache
        id: turbo-cache
        uses: actions/cache@v2
        with:
          path: .turbo
          key: turbo${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ github.ref_name }}-

      # Should be fast as this is requiring the ts build to succeed (and thus having cache)
      - name: Run Build
        run: yarn turbo run build:ci --cache-dir=".turbo" && yarn tsc --build

      - name: Delete contents in dist/
        run: rm -rf dist/*
        
      - name: Run local build for package
        run: yarn workspace ${{ matrix.package }} build

      - name: Publish package
        run: |
          yarn workspace ${{ matrix.package }} release --preid "dev.$(date +%s)-$(git rev-parse --short HEAD)"
          yarn workspace ${{ matrix.package }} npm publish || true
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
